<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_sample.png</name>
   <tag></tag>
   <elementGuidId>dd5a799d-4ad0-412b-80f5-b430e901e535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/a[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>811588f1-80cf-4f7a-bb9c-d1c46863ed0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/sample.png</value>
      <webElementGuid>d60882a8-95e2-499e-9975-8ad41189308c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sample.png</value>
      <webElementGuid>ed6a3c75-141d-4785-975e-7dec7c5625ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/a[16]</value>
      <webElementGuid>fe078723-eb66-4db7-b39f-65532d2c3a1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/a[16]</value>
      <webElementGuid>9c115397-54ef-41cf-b625-3fbeb3155069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'sample.png')]</value>
      <webElementGuid>832284aa-9a4b-4065-96ea-e3a29c6e79ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate_JUNIT.png'])[1]/following::a[1]</value>
      <webElementGuid>be4b6d56-4c1c-46be-b1f1-a5be27937699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='demo.txt'])[1]/following::a[2]</value>
      <webElementGuid>5627f2bc-87bf-43be-b129-e044dbea43e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description.PNG'])[1]/preceding::a[1]</value>
      <webElementGuid>98b2754d-449e-4465-aaa7-febff5b4eb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='t2.jpg'])[1]/preceding::a[2]</value>
      <webElementGuid>3b85a05a-fe31-4215-a90b-f7f656ff851d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sample.png']/parent::*</value>
      <webElementGuid>6bbc16c8-6b6b-40b7-a4de-0ac209e6c6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/sample.png')]</value>
      <webElementGuid>9a9cb27d-99bb-47ec-a5d0-9a97dfce9f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[16]</value>
      <webElementGuid>47a19f53-501a-400b-b363-f70419f15838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/sample.png' and (text() = 'sample.png' or . = 'sample.png')]</value>
      <webElementGuid>1b5fcaea-e81a-4285-992a-1c0b59bcfa0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
